[montecarlo]
ntrajectories = 50
end_time = 10.0

[sampler]
strategy = "montecarlo"

[runtime]
loglevel = "INFO"

[trajectory]
step_size = 0.01
targetscore = 0.95

[model]
epsilon = 0.2

[runner]
type = "asyncio"
nworkers=2
