[ams]
ntrajectories = 25
nsplititer = 200

[sampler]
strategy = "ams"

[runtime]
loglevel = "INFO"

[trajectory]
end_time = 10.0
step_size = 0.01
targetscore = 0.95

[model]
epsilon = 0.2

[runner]
type = "asyncio"
nworker_init=2
nworker_iter=1
