[ams]
ntrajectories = 50
nsplititer = 1000

[sampler]
strategy = "ams"

[runtime]
loglevel = "INFO"
diagnostics = ['test']

[trajectory]
end_time = 20.0
step_size = 0.01
targetscore = 1.05

[model]
inv_temperature = 3.67

[runner]
type = "asyncio"
nworker_init=8
nworker_iter=1

[test]
trigger_type = "score"
score_min = 0.0
score_max = 1.05
n_levels = 22

[database]
path = "./testDB.tdb"
