[tams]
ntrajectories = 100
nsplititer = 1000
loglevel = "INFO"
walltime = 500.0


[trajectory]
end_time = 3153600000
step_size = 86400
targetscore = 1.00
sparse_freq = 10

[model]
noise_level = 0.1
E_A = 0.25

[runner]
type = "asyncio"
nworker_init=2
nworker_iter=2

[database]
path = "MOCTest.tdb"
