[sampler]
strategy = "ams"

[ams]
ntrajectories = 20
nsplititer = 200
variant = "tams"
end_time = 20.0
l_j = 2

[runtime]
loglevel = "INFO"
plot_diagnostics = true

[trajectory]
step_size = 0.005
targetscore = 0.95
sparse_freq = 10

[model]
exec = "./boussinesq.exe"
init_state = "./ONState.bin"
size_M = 40
size_N = 80
epsilon = 0.05
K = 7

[runner]
type = "dask"
nworkers=2

[database]
path = "2DBoussinesqCpp.tdb"
