[ams]
ntrajectories = 32
nsplititer = 5000
variant = "tams"
end_time = 5.0

[sampler]
strategy = "ams"

[runtime]
loglevel = "INFO"

[trajectory]
step_size = 0.01
# 6 sigma
targetscore = 4.24264068712

[model]
theta = 1.0 
epsilon = 0.50
