[tams]
ntrajectories = 20
nsplititer = 1000
loglevel = "INFO"
walltime = 7200.0
diagnostics = true

[trajectory]
end_time = 20.0
step_size = 0.01
targetscore = 0.96
sparse_freq = 50

[model]
size_M = 40
size_N = 80
epsilon = 0.01
K = 7
score_method = "PODdecomp"
pod_data_file = "/Users/lucas/Documents/Work/UU/Boussinesq/Instanton/POD_Decomp/POD_decomp_InstModes.nc"
pod_d0 = 100.0

[runner]
type = "dask"
nworker_init=5
nworker_iter=2

[dask]
backend = "local"

[database]
path = "2DBoussinesq_K7_dt0p01_eps0p02_Inst.tdb"
