[tams]
ntrajectories = 100
nsplititer = 1000
loglevel = "INFO"
walltime = 200.0
diagnostics = false
deterministic = true

[trajectory]
end_time = 10.0
step_size = 0.01
targetscore = 0.95
#sparse_int = 17

[model]
test_param = "toto"
noise_amplitude = 0.4

[runner]
type = "asyncio"
nworker_init=2
nworker_iter=2

[dask]
backend = "local"

[database]
path = "3DTestDW"
archive_discarded = true
