[tams]
ntrajectories = 100
nsplititer = 1000
loglevel = "INFO"


[trajectory]
end_time = 3153600000
step_size = 86400
targetscore = 1.00
sparse_freq = 10
stoichforcing = 0

[model]
test_param = "toto"

[runner]
type = "asyncio"
nworker_init=2
nworker_iter=2

[database]
path = "MOCTest.tdb"
