[tams]
ntrajectories = 200
nsplititer = 1000
loglevel = "WARNING"
walltime = 200.0
diagnostics = false

[trajectory]
end_time = 10.0
step_size = 0.01
targetscore = 0.95

[model]
noise_amplitude = 0.3

[runner]
type = "asyncio"
nworker_init=4
nworker_iter=2
